name: build-and-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read    # This is required for actions/checkout
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: NotifyRss
      - name: Download file from S3
        env:
          CDK_CONTEXT_JSON_URI: ${{ secrets.CDK_CONTEXT_JSON_URI }}
        run: aws s3 cp $CDK_CONTEXT_JSON_URI ./
      - name: Test
        run: npm t
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Deploy
        if: startsWith(github.ref, 'refs/heads/main')
        run: npm run cdk -- deploy
